services:
  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j-local
    ports:
      - "7687:7687" # Bolt
      - "7474:7474" # HTTP
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./scripts:/scripts:ro
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1;"]
      interval: 3s
      timeout: 3s
      retries: 5
